name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build-and-test:
    env:
      REDISCLOUD_URL: 'redis://127.0.0.1:6379'
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/chikav1?schema=public'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.16.1
        uses: actions/setup-node@v2
        with:
          node-version: '14.16.1'

      - name: Install dependencies
        run: yarn

      - name: Set up databases
        run: yarn docker:up

      - name: Build
        run: yarn build:dev

      - name: Test
        run: yarn test:ci

      - name: Upload report to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
